### ISSUE TITLE
REST chapter to cover what has been added in Lift 2.0

### ISSUE THREAD

**Issue by wadearnold** [tjweir/liftbook#20]
The lift 2.0 release notes speak of a "Powerful, concise REST support" and all that is to show for it is the documentation on assembla. I am interested to see how the "new" functionality fits into the demo application of the book.
https://liftweb.assembla.com/wiki/show/liftweb/REST_Web_Services

**Comment by dchenbecker** [comment]
Initial draft revision of the Web Services chapter is now committed.

**Comment by wadearnold** [comment]
THANK YOU THANK YOU THANK YOU!!!

**Comment by dchenbecker** [comment]
So, I'm going to assume that that's a vote to close it ;)
