### ISSUE TITLE
Lift screens

### ISSUE THREAD

**Issue by wadearnold** [tjweir/liftbook#21]
There has been a lot of talk about how awesome Lift Screens are in 2.0 and I guess I don't get it. The assembla documentation is almost to basic of an example. 

https://liftweb.assembla.com/wiki/show/liftweb/Lift's_Screen

**Comment by goldmar** [comment]
This book has got me up and running with Lift but I'd really like to see some more examples of LiftScreen. Currently LiftScreen is not usable for me because it's extremely hard to find out how things work  :-(
