### ISSUE TITLE
google map api error

### ISSUE THREAD

**Issue by NKJason** [tjweir/liftbook#26]
hello

I want set google map api.

ex)  ＜script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=true_or_false&amp;key=ABQIAAAAbatLJBm-S8hZ??????????Kjn5hrRSDxT3TEkaetXhQ1WV8hEqirn9k6T7JkK77gvngPOQ" type....

but.. this script set is error.

I want to easily solve this problem,

But, I did not find the solution of this problem.

Please teach a solution.

thank you.

**Comment by NKJason** [comment]
ex)  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;...

**Comment by dchenbecker** [comment]
You need to put your script src inside a scala.xml.Unparsed:

```
    <script src={Unparsed("http://maps.google.com/maps?file=api&v=2...")} />
```

otherwise, the "&" gets escaped to "&amp;". See

http://scala.sygneca.com/faqs/xml

**Comment by NKJason** [comment]
thank you. but new error message. 

1Uncaught TypeError: Object #<a Document> has no method 'write'
GScriptmaps:1
GLoadMapsScriptmaps:1
(anonymous function)

what is this error message? please answer :-)

**Comment by dchenbecker** [comment]
Lift serves pages as XHTML by default. Google Maps does not work with XHTML. You should be able to search the Liftweb group for answers on how to fix that:

http://groups.google.com/group/liftweb/
