### ISSUE TITLE
Possible error in: "Coordinating Between Multiple Comet Clients"

### ISSUE THREAD

**Issue by mads-hartmann** [tjweir/liftbook#27]
Hey guys,

I think I've stumbled upon an error in the book on page 157. I think you're missing the override keyword on the methods localSetup and localShutdown

Thanks,
Mads Hartmann

**Comment by dchenbecker** [comment]
Thanks, I'll get that fixed.

**Comment by mads-hartmann** [comment]
Cool, thanks :)

**Comment by dchenbecker** [comment]
Added missing "override" to Comet listing

Closed by 1f42e11f6872a493e754555cdd0fda62aaa5c80f

Thanks to Mads for catching this.
