### ISSUE TITLE
Loggin section uses deprecated method

### ISSUE THREAD

**Issue by jeppenejsum** [tjweir/liftbook#33]
The correct use of logging is on the wiki

**Comment by dchenbecker** [comment]
Could you be more specific? Remember that PocketChange is a Lift _2.0_ app

**Comment by jeppenejsum** [comment]
Ok, I'm a little unsure about the exact deprecation of the "old-style" logging, but believe it was from 2.0-M3 as written here https://www.assembla.com/wiki/show/liftweb/Logging

The new style was included from 2.0-M3 and so is in 2.0

**Comment by dchenbecker** [comment]
Revised logging appendix to make it not ancient

Closed by 81be3cf8a9ba20e7aa620d2b5575854ea472c3be
Closed by 81be3cf8a9ba20e7aa620d2b5575854ea472c3be

Also updated PocketChange to reflect the new usage
