### ISSUE TITLE
Sample code of URL rewrite has compilation error.

### ISSUE THREAD

**Issue by xiaowl** [tjweir/liftbook#35]
In sec 3.7 code list 3.6, A Complex Rewrite Example, there is a val declaration,
val rewriter = {
 case RewriteRequest(ParsePath(username :: Nil, _, _, _),
 DeleteRequest,
 httpreq)
 if isMgmtSubnet(httpreq.getRemoteHost()) =>
 RewriteResponse(deleteUser :: Nil, Map(username -> username))
 }
The Scala compiler will compile the case statement to a Functionk or PartialFunction object, but if you don't specify the val type, there should be a compilation error. I think it should be,
val rewriter:PartialFunction[RewriteRequest,RewriteResponse] = {...}
My Scala version is 2.8.1.final.
This book is great, thanks for your work :-)
Thanks,
Kevin Xiao

**Comment by dchenbecker** [comment]
Updated broken rewrite example listing

Closed by 26ddae7d0d80b33b68e91c513f2c194f8130e069
