### ISSUE TITLE
Misprints in 13.5

### ISSUE THREAD

**Issue by qrilka** [tjweir/liftbook#39]
In

"It is developer by Jabber [E]  [E] http://xmpp.org/about/jabber.shtml open-source community. Lift provides an XMPP dispatcher implementation that you application can use to receive instant messages, manage rosters etc."

looks like "developer" should be "developed" and "you application" should be "your application".

**Comment by dchenbecker** [comment]
Added Designer-Friendly and CSS info

Closed by e48ff78bc0319ae5c09b126dc5a225547192e296 (CSS transforms)
Closed by e48ff78bc0319ae5c09b126dc5a225547192e296 (DFT)
Closed by e48ff78bc0319ae5c09b126dc5a225547192e296 (minor fixes to XMPP section wording)
Closed by e48ff78bc0319ae5c09b126dc5a225547192e296 (minor fix to rewrite example)
