### ISSUE TITLE
Listing 2.2 Pocket Change Account Entity. Error in import of Empty

### ISSUE THREAD

**Issue by gdepourtales** [tjweir/liftbook#46]
When using Lift v2.3 with Scala 2.8.1, the class Empty is declared in net.liftweb.common package and available in lift-common_2.8.1-2.3. In Listing 2.2 the third import should be import `_root_.net.liftweb.common.Empty` instead of import `_root_.net.liftweb.util.Empty`

**Comment by dchenbecker** [comment]
The book is still targeted at 2.0 (I know, I need to update it!), so this will have to wait a bit.

**Comment by gdepourtales** [comment]
OK Thanks for the precision on the targeted version
